stages:
  - test
  - deploy

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

deploy_to_preprod:
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"'
  script:
    - curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_uC46fEIrAc7SIJelykvXQn4p75el/3DKKwgyd0M

deploy_to_prod:
  stage: deploy
  only:
    - main
  script:
    - npm install -g vercel
    - vercel --token=$VERCEL_TOKEN --prod
