stages:
  - deploy

deploy_to_develop:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
  script:
    - curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_uC46fEIrAc7SIJelykvXQn4p75el/ot0EpUFUSk

deploy_to_prod:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "merge_request"'
  script:
    - npm install -g vercel
    - vercel --token=https://api.vercel.com/v1/integrations/deploy/prj_uC46fEIrAc7SIJelykvXQn4p75el/yUB8SeMwsE --prod
